### ISSUE TITLE
[Suggestion] Node Canvas like interface

### ISSUE THREAD

**Issue by Snowflake107** [DjDeveloperr/deno-canvas#2]
It'd be great if you could implement **[node-canvas](https://github.com/Automattic/node-canvas)** like interface to `deno-canvas` so that we don't have to rewrite everything 👍

**Comment by DjDeveloperr** [comment]
I've been using node-canvas until I moved on to Deno, there isn't much to change except the `createCanvas` from what I know. Maybe I'm not getting it right, can you explain what you have to rewrite exactly? 

For example, the "Quick Example" mentioned in the README of node-canvas,
```js
// node-canvas
const { createCanvas, loadImage } = require('canvas')
const canvas = createCanvas(200, 200)
// deno-canvas
import Canvas, { loadImage } from 'deno-canvas-url'
const canvas = Canvas.MakeCanvas(200, 200)

const ctx = canvas.getContext('2d')

// ... rest code
```

**Comment by DjDeveloperr** [comment]
@Snowflake107 is there anything else to add 👀

**Comment by Snowflake107** [comment]
@DjDeveloperr how's loadFont
