### ISSUE TITLE
drawImage does not support using a canvas as the image

### ISSUE THREAD

**Issue by glenmurphy** [DjDeveloperr/deno-canvas#22]
In the browser, drawImage can take a canvas in place of an image as an argument, which is very useful for when doing drawing/compositing operations. The following would be expected to work:

```
import { createCanvas} from "https://deno.land/x/canvas/mod.ts";
let canvas_a = createCanvas(800, 600);
let canvas_b = createCanvas(800, 600);
canvas_a.getContext("2d").drawImage(canvas_b, 0, 0);
```

When using deno-canvas, because drawImage expects an Image, the following error is thrown:

```
error: Uncaught (in promise) TypeError: k.width is not a function
                    arguments[3] || k.width(),
                                      ^
    at q.drawImage (https://deno.land/x/canvas@v1.3.0/src/lib.js:2660:39)
```

You can work around this with:

 ```
 if (environment() == 'deno')
     ctx.drawImage(await loadImage(canvas.toBuffer()), 0, 0);
 else
     ctx.drawImage(canvas, 0, 0);
```

But this workaround generates a dependency on async, and makes sharing code across browser and client harder.

**Comment by DjDeveloperr** [comment]
It should be possible to add support to directly pass canvas, I'll look into it in few hours

**Comment by DjDeveloperr** [comment]
Now supported in v1.4.0
