### ISSUE TITLE
when run on mac with arm64:

### ISSUE THREAD

**Issue by cputnam-a11y** [DjDeveloperr/deno-canvas#35]
➜  Deno_Canvas deno run main.ts
✅ Granted ffi access to "/Users/charlesp/Tests/Deno_Canvas/node_modules/.deno/canvas@2.11.2/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/build/Release/canvas.node".
dyld[48551]: missing symbol called
[1]    48551 abort      deno run main.ts
➜  Deno_Canvas

**Comment by Macil** [comment]
You're using https://github.com/Automattic/node-canvas, not this project.
