### ISSUE TITLE
__dirname is not defined with Deno 2 RC

### ISSUE THREAD

**Issue by littledivy** [DjDeveloperr/deno-canvas#41]
```
error: Uncaught (in promise) ReferenceError: __dirname is not defined
        Ca = za ? require("path").dirname(Ca) + "/" : __dirname + "/",
                                                      ^
    at Module.<anonymous> (https://deno.land/x/canvas@v1.4.1/src/lib.js:3784:55)
    at init (https://deno.land/x/canvas@v1.4.1/src/canvaskit.ts:9:20)
    at init (https://deno.land/x/canvas@v1.4.1/src/canvas.ts:9:18)
    at https://deno.land/x/canvas@v1.4.1/mod.ts:3:22
```

https://github.com/DjDeveloperr/deno-canvas/blob/117afa232c680b73bf989de27af013c21ce310f6/src/lib.js#L3776-L3784

`window` global was removed and `process` global was added in Deno 2. This causes deno_canvas to enter the Node.js-specific path and access __dirname.

Ref https://github.com/denoland/deno/issues/25928

**Comment by wesbos** [comment]
thanks for the quick fix. My deno deploy app just started crashing after not touching it for a few months - turned out to be this

**Comment by DjDeveloperr** [comment]
this is interesting though, is deno 2 supposed to be deployed on existing apps without any new deployments? cc @littledivy 
since there are breaking changes, this seems problematic

**Comment by arnauorriols** [comment]
> this is interesting though, is deno 2 supposed to be deployed on existing apps without any new deployments? cc @littledivy since there are breaking changes, this seems problematic

No, that was a bug in Deploy. We are still defining how to handle the upgrade to Deno 2.0, and will communicate it properly once we have a clear decision.

**Comment by wesbos** [comment]
Ahh okay - I thought I had not locked my deno version down and it just upgraded it. 

It happened with Node on Render once and I learned to lock my versions down.

**Comment by YairRand** [comment]
This bug appears to have resurfaced. Exact same error message. Running deno 2.4.4.
