### ISSUE TITLE
Garbled characters in Japanese?

### ISSUE THREAD

**Issue by K-REBO** [DjDeveloperr/deno-canvas#8]
I draw Japanese letter. Is it the problem of my computer?
![2021-05-31_22-57](https://user-images.githubusercontent.com/58938944/120204888-454b1a00-c264-11eb-926f-2540a476feac.png)
someone know how to fix it?
``` javascript
ctx.font = "40px serif"
```
i use this font.

**Comment by DjDeveloperr** [comment]
I'm not sure what causes it, maybe try using a custom font which supports Japanese? I have seen such thing happen on my system too sometimes but works on vps. I will investigate more today.

**Comment by DjDeveloperr** [comment]
So this module can't access any system fonts by default. So you'll have to use `loadFont` method to add font for Japanese. I'll close this issue for now, if it still occurs after loading font, let me know I'll re open the issue
